bbox = [-6.8596, -11.0020, 19.7872, 22.2767]

resolution = 5
duration = 600

[network_params]
bandwidth_kbits = 10_000
min_elevation = 40
ground_station_connection_type = "all"

[compute_params]
vcpu_count = 2
mem_size_mib = 512
kernel = "server-linux.bin"
rootfs = "server.img"
disk_size_mib = 50

[[shell]]
planes = 72
sats = 22
altitude_km = 550
inclination = 53.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 32
sats = 50
altitude_km = 1110
inclination = 53.8
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 8
sats = 50
altitude_km = 1130
inclination = 74.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 5
sats = 75
altitude_km = 1275
inclination = 81.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 6
sats = 75
altitude_km = 1325
inclination = 70.0
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[ground_station]]
name = "tracker"
# Azure South Africa North (Johannesburg)
lat = -26.189948
long = 28.031616

[ground_station.compute_params]
vcpu_count = 4
mem_size_mib = 4096
kernel = "client-linux.bin"
rootfs = "tracker.img"

[[ground_station]]
#name = "Accra"
name = "1"
lat = 5.548854
long = -0.220214

[ground_station.compute_params]
vcpu_count = 4
mem_size_mib = 4096
kernel = "client-linux.bin"
rootfs = "client.img"
disk_size_mib = 500

[[ground_station]]
#name = "Abuja"
name = "2"
lat = 9.054770
long = 7.483895

[ground_station.compute_params]
vcpu_count = 4
mem_size_mib = 4096
kernel = "client-linux.bin"
rootfs = "client.img"
disk_size_mib = 500

[[ground_station]]
#name = "Yaounde"
name = "3"
lat = 3.872887
long = 11.520264

[ground_station.compute_params]
vcpu_count = 4
mem_size_mib = 4096
kernel = "client-linux.bin"
rootfs = "client.img"
disk_size_mib = 500
